spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wxtest?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: root

mybatis:
  type-aliases-package: com.example.backend
  config-location: classpath:mybatis.xml